name: Build and Test

on:
 push:
   branches:
     - main
     - staging
     - dev
 pull_request:
   branches:
     - main
     - staging
     - dev

jobs:
 build:
   runs-on: windows-latest

   steps:
   - name: Checkout code
     uses: actions/checkout@v2

   - name: Setup MSBuild
     uses: microsoft/setup-msbuild@v1

   - name: Restore NuGet packages
     run: nuget restore

   - name: create PFX file
     run: |
         $pfxFile = Join-Path $env:CertDir $env:Certname
         $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.CERT_KEY }}")
         [System.IO.File]::WriteAllBytes($pfxFile, $pfx_cert_byte)]
     env: 
       CertDir: D:\a\document-generator\document-generator\ShapeHandler\
       Certname: ShapeHandler_TemporaryKey.pfx

   - name: Install certificate
     run: |
         $pfxFile = Join-Path $env:CertDir $env:Certname
            $pfxPassword = "${{ secrets.CERT_PASSWORD }}"
            $securePassword = ConvertTo-SecureString -String $pfxPassword -Force -AsPlainText
            Import-PfxCertificate -FilePath $pfxFile -CertStoreLocation Cert:\LocalMachine\Root -Password ""
     env: 
       CertDir: D:\a\document-generator\document-generator\ShapeHandler\
       Certname: ShapeHandler_TemporaryKey.pfx

   - name: Build with MSBuild
     run: msbuild /p:Configuration=Release /p:AppxPackageSigningEnabled=${{ env.SigningEnabled }}
     env:
       SigningEnabled: false

   - name: Upload build artifacts
     uses: actions/upload-artifact@v4
     with:
       name: build-artifacts
       path: |
         **/bin/Release/
         **/obj/Release/

 test:
   runs-on: windows-latest
   needs: build

   steps:
   - name: Checkout code
     uses: actions/checkout@v2

   - name: Download build artifacts
     uses: actions/download-artifact@v4
     with:
       name: build-artifacts
       path: ./build

   - name: Run tests
     run: dotnet test ./build --no-build --verbosity normal --logger "trx;LogFileName=test_results.trx"

   - name: Upload test results
     uses: actions/upload-artifact@v4
     with:
       name: test-results
       path: test_results.trx
