name: Build and Test

on:
 push:
   branches:
     - main
     - staging
     - dev
 pull_request:
   branches:
     - main
     - staging
     - dev

jobs:
 build:
   runs-on: windows-latest

   steps:
   - name: Checkout code
     uses: actions/checkout@v2

   - name: Setup MSBuild
     uses: microsoft/setup-msbuild@v1

   - name: Restore NuGet packages
     run: nuget restore

   - name: Decode PFX
     run: |
        $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.CERT_KEY }}")
        $currentDirectory = "D:\a\document-generator\document-generator\ShapeHandler\"
        $certificatePath = Join-Path -Path $currentDirectory -ChildPath $env:SigningCertificate
        [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)
        $securePassword = ConvertTo-SecureString -String "${{ secrets.CERT_PASS }}" -AsPlainText -Force
        Import-PfxCertificate -FilePath $certificatePath -CertStoreLocation Cert:\LocalMachine\My -Password $securePassword

     env:
       SigningCertificate: ShapeHandler_TemporaryKey.pfx

   - name: Build with MSBuild
     run: msbuild /p:Configuration=Release

   - name: Upload build artifacts
     uses: actions/upload-artifact@v4
     with:
       name: build-artifacts
       path: |
         **/bin/Release/
         **/obj/Release/

 test:
   runs-on: windows-latest
   needs: build

   steps:
   - name: Checkout code
     uses: actions/checkout@v2

   - name: Download build artifacts
     uses: actions/download-artifact@v4
     with:
       name: build-artifacts
       path: ./build

   - name: Run tests
     run: dotnet test ./build --no-build --verbosity normal --logger "trx;LogFileName=test_results.trx"

   - name: Upload test results
     uses: actions/upload-artifact@v4
     with:
       name: test-results
       path: test_results.trx
