name: Build and Test

on:
 push:
   branches:
     - main
     - staging
     - dev
 pull_request:
   branches:
     - main
     - staging
     - dev

jobs:
 build:
   runs-on: windows-latest

   steps:
   - name: Checkout code
     uses: actions/checkout@v2

   - name: Setup MSBuild
     uses: microsoft/setup-msbuild@v1

   - name: Restore NuGet packages
     run: nuget restore

   - name: create PFX file
     run: |
         $pfxCertFilePath = Join-Path -Path $env:CertDir -ChildPath $env:CertName
         [System.IO.File]::WriteAllBytes($pfxCertFilePath, [System.Convert]::FromBase64String("${{secrets.CERT_KEY}}"))
         # $codeSigningCert = Import-PfxCertificate -FilePath $pfxCertFilePath -Password $("${{secrets.CERT_PASS}}" | ConvertTo-SecureString -AsPlainText -Force) -CertStoreLocation Cert:\CurrentUser\My
     env:
        CertDir: D:\a\document-generator\document-generator\ShapeHandler\
        CertName: ShapeHandler_TemporaryKey.pfx

   - name: Build with MSBuild
     run: msbuild /p:Configuration=Release /p:PackageCertificateKeyFile=$env:SigningCertificate /p:PackageCertificatePassword=$env:PrivateKey /p:PackageCertificateThumbprint=$env:Thumbprint /p:AppxPackageSigningEnabled=true
     env:
       SigningEnabled: false
       PrivateKey: ${{secrets.CERT_KEY}}
       Thumbprint: ${{secrets.CERT_THUMBPRINT}}
       SigningCertificate: ShapeHandler_TemporaryKey.pfx

   - name: Upload build artifacts
     uses: actions/upload-artifact@v4
     with:
       name: build-artifacts
       path: |
         **/bin/Release/
         **/obj/Release/

 test:
   runs-on: windows-latest 
   needs: build

   steps:
   - name: Checkout code
     uses: actions/checkout@v2

   - name: Download build artifacts
     uses: actions/download-artifact@v4
     with:
       name: build-artifacts
       path: ./build

   - name: Run tests
     run: dotnet test ./build --no-build --verbosity normal --logger "trx;LogFileName=test_results.trx"

   - name: Upload test results
     uses: actions/upload-artifact@v4
     with:
       name: test-results
       path: test_results.trx
