name: Test Repo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x' # Specify the .NET version you are using

    - name: Install dependencies
      run: dotnet restore

    - name: Run tests
      run: dotnet test --no-restore
