name: .NET Framework CI

on:
  push:
    branches:
      - main
      - staging
      - dev
  pull_request:
    branches:
      - main
      - staging
      - dev

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Framework
      uses: actions/setup-dotnet@v1

    - name: Restore dependencies
      run: |
        echo "Restoring dependencies..."
        nuget restore

    - name: Lint code
      run: |
        echo "Linting code..."
        dotnet format

    - name: Build solution
      run: |
        echo "Building solution..."
        msbuild /p:Configuration=Release

    - name: Run tests
      run: |
        echo "Running tests..."
        vstest.console.exe **\*Tests.dll
